Parameters:
  RemoteRoleARN:
    Type: String
  SshCidr:
    Type: String
Resources:
  CallerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CallerRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  CallerRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CallerRolePolicy
      PolicyDocument:
        Statement:
        - Sid: CrossAccountAssumeRolePermissions
          Action:
            - sts:AssumeRole
          Effect: Allow
          Resource:
            - !Ref RemoteRoleARN
      Roles:
        - !Ref CallerRole

  Role1:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Role1
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  Role1Policies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Role1Policy
      PolicyDocument:
        Statement:
        - Action:
            - ec2:describe*
          Effect: Allow
          Resource:
            - '*'
      Roles:
        - !Ref Role1

  InstanceProfile1:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref CallerRole
#        - !Ref Role1
      InstanceProfileName: InstanceProfile1
  
  Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref InstanceProfile1
      ImageId: ami-ff4ea59d
      KeyName: 2013-04
      InstanceType: t2.nano
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      Tags: 
        - Key: Name
          Value: Instance Profile Test Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SshCidr

Outputs:
  IpAddress: 
    Value: !GetAtt Instance1.PublicIp

