AWSTemplateFormatVersion: '2010-09-09'
Description: Security group with AWS::NoValue for CidrIp property.
Parameters:
  Cidr1:
    Default: ''
    Type: String 
  Cidr2:
    Default: ''
    Type: String 

Mappings: {}

Conditions:
  HasCidr1: !Not [ !Equals [ !Ref Cidr1, '' ] ]
  HasCidr2: !Not [ !Equals [ !Ref Cidr2, '' ] ]


Resources:
  TestSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group with AWS::NoValue for CidrIp Property
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !If [ HasCidr1, !Ref Cidr1, 'AWS::NoValue' ]
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !If [ HasCidr2, !Ref Cidr2, 'AWS::NoValue' ]

# Conclusion -Single NoValue invalidates all ingress rules. NoValue acts like null.

