AWSTemplateFormatVersion: '2010-09-09'
Description: Optional security group rule
Parameters:
  Cidr1:
    Default: '0.0.0.0/32'
    Type: String 
  Cidr2:
    Default: '0.0.0.0/32'
    Type: String 

Mappings: {}

Resources:
  TestSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group - Default value for an optional rule
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'
        # Optional rule. Using AWS::NoValue invalidated the whole list of this property so just use the invalid Cidr.
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !Ref Cidr1
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !Ref Cidr2

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1e91817d
      InstanceType: t2.nano
      SecurityGroupIds:
        - !Ref TestSecurityGroup1
