AWSTemplateFormatVersion: '2010-09-09'
Description: Test alarm configuration
Parameters:
    SNSAlertEmail:
        Description: Email address alarms are sent to
        Type: String

Mappings: {}

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for monitoring FTT Batch job
      Subscription:
        - Endpoint: !Ref SNSAlertEmail
          Protocol: email

  Alarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 60 EvaluationPeriods 2
      AlarmName: P60EP3
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 60
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: ignore # bad choice for SampleCount

  Alarm2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 120 EvaluationPeriods 1
      AlarmName: P120EP1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 120
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: ignore #bad choice for SampleCount

  Alarm3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 60 EvaluationPeriods 2
      AlarmName: P60EP3Bad
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 60
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: breaching

  Alarm4:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 120 EvaluationPeriods 1
      AlarmName: P120EP1Bad
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 120
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: breaching

  Alarm5:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 60 EvaluationPeriods 1
      AlarmName: P60EP1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 60
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: breaching

  Alarm5:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: Period 60 EvaluationPeriods 1
      AlarmName: P60EP1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref Topic
      MetricName: LastResult
      Namespace: Test1
      Dimensions: 
        - Name: Env
          Value: dev
      Period: 60
      Statistic: SampleCount
      Threshold: 1
      Unit: None
      TreatMissingData: breaching
