AWSTemplateFormatVersion: '2010-09-09'
Description: Optional security group rule
Parameters: {}
Mappings: {}

Resources:
  TestSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: one port 22, two port 80.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/32
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/32

