AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack to test conditional resource creation.
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: mydbidentifier1 
  MasterUserName:
    Description: The change of this parameter will cause replacement.
    Type: String
    Default: dbuser1
  MasterUserPassword:
    Type: String
    NoEcho: true
  
Mappings: {}

Resources:

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      AllocatedStorage: '50'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 14
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Ref DBInstanceIdentifier    # By setting this parameter, unless you change this value, instance won't be replaced with parameter change.
      Engine: postgres
      EngineVersion: 9.6.2
      MasterUsername: !Ref MasterUserName
      MasterUserPassword: !Ref MasterUserPassword
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: false
      StorageType: gp2
      Tags:
      - Key: Name
        Value: !Sub build-db
